### ISSUE TITLE
root access in docker

### ISSUE THREAD

**Issue by ashkan2200** [dealii/docker-files#13]
Hi,
I tried using docker container with dealii and I go into dealii user. 
I think it is better if we can directly enter the root user as it is with most other containers. 

For me the issue is that I would like to install other things with apt-get which requires the root.

Ashkan.

**Comment by Rombur** [comment]
you should be able to do `docker run --user root ...` and be root.

**Comment by ashkan2200** [comment]
my bad. It seems that I did something wrong in the process.
