### ISSUE TITLE
Cannot pull dealii and dealii-bare

### ISSUE THREAD

**Issue by Rombur** [dealii/docker-files#2]
I don't know who owns the dealii user on dockerhub but I can't pull dealii and dealii-bare. I get the following error:

docker pull dealii/dealii
Using default tag: latest
Pulling repository docker.io/dealii/dealii
Tag latest not found in repository docker.io/dealii/dealii

Apparently there was a problem during the build **https://hub.docker.com/r/dealii/dealii/builds/**

**Comment by tjhei** [comment]
I think that the current state is incomplete. I have a working docker setup at https://github.com/tjhei/docker-files/tree/experimental see #3

**Comment by luca-heltai** [comment]
Actually, the current state is working, but not on docker (where it times out). You can find some late builds on https://hub.docker.com/u/heltai/. 

These builds use clang+gfortran.

**Comment by Rombur** [comment]
OK thanks.

**Comment by luca-heltai** [comment]
I'm building now the dealii-bare-system image, if you are interested in that too.

**Comment by Rombur** [comment]
@luca-heltai Thanks, I will try it too.
