### ISSUE TITLE
[RFC] Rename images?

### ISSUE THREAD

**Issue by luca-heltai** [dealii/docker-files#6]
In view of moving images under official dealii namespace on dockerub, how about we rename them in the following way:
- dealii/base-system
  
  dealii/dealii:bare-debug
  dealii/dealii:bare-release
  dealii/dealii:bare-debug-release
- dealii/external-libraries
  
  dealii/dealii:debug
  dealii/dealii:release
  dealii/dealii:debug-release

**Comment by bangerth** [comment]
Instead of `dealii/dealii:bare-debug-release` why not `dealii/dealii` or `dealii/dealii:bare`? This is the default configuration, so omitting `debug-release` would make things simpler for most people.

**Comment by tjhei** [comment]
I think the stuff after ":" (the TAG) should be used for versioning and not for different variants. Otherwise there is no way to make images for the last release (:v8.4.1) and the current master (:latest). Or maybe I am missing something?

**Comment by luca-heltai** [comment]
I think `dealii/dealii:

**Comment by luca-heltai** [comment]
Btw: the tag, in docker naming conventions, are precisely called variants. I think this is exactly what tags were intended for...

**Comment by tjhei** [comment]
Sorry for neglecting this repo and your question for so long. I definitely need 8.4.1 images, which we are not building right now. I also think the latest release should be the default (and get the "latest" tag), but that is not particular important to me. 

I think it would make sense to tag something like ``(v.8.4.1|v8.5.pre)-(bare|fulldeps)-(debug|release|debugrelease)``.

Speaking of which, you merged the PR but I don't see the new images at https://hub.docker.com/u/dealii/dashboard/ ?
