### ISSUE TITLE
fulldeps package is missing p4est

### ISSUE THREAD

**Issue by tjhei** [dealii/docker-files#8]
```
$ docker run -it --rm dealii/dealii:v8.5.0-gcc-mpi-fulldepsmanual-debugrelease /bin/bash
dealii@669f2162dbcb:~$ grep DEAL_II_WITH_P4EST dealii-v8.5.0/include/deal.II/base/config.h
/* #undef DEAL_II_WITH_P4EST */
```
It would make sense to specify ``-D DEAL_II_W_TH_P4EST=on`` (also for the other dependencies!), so the deal.II configure will fail.

**Comment by luca-heltai** [comment]
I don't know why it was not picked up. It is installed though. :( I'll look into this after the build on top of the new ubuntu images is ready.

**Comment by luca-heltai** [comment]
Won't fix `fulldepsmanual`. We'll just remove that configuration.

**Comment by tjhei** [comment]
:+1: thanks!
